name: Another-merge Dependabot PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup:
    runs-on: ubuntu-20.04
    name: Setup
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed_files
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'dependabot')
        uses: lots0logs/gh-action-get-changed-files@2.2.2
        with:
          token: ${{ secrets.ACT_TOKEN }}

      - name: Check modified files
        id: check_modified
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'dependabot')
        run: |
          echo "::set-output name=version_modified::$(jq '. | contains(["actions-runner/VERSION"])' ${HOME}/files_modified.json)"

          COMMIT_MSG=$(git log --format=%B -n 1 ${{ github.event.before }})

      - name: Increment version if not modified
        if: ${{ !steps.check_modified.outputs.version_modified && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'dependabot') }}
        run: |
          SEM_VER=$(cat VERSION | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
          COMMIT_MSG=$(git log --format=%B -n 1 ${{ github.event.after }})

          # Write files
          echo $SEM_VER > VERSION
          if [ -f CHANGELOG.md ]; then
            sed -i "12i ## [${SEM_VER}]\n### Changed\n* ${COMMIT_MSG}" CHANGELOG.md
            git add CHANGELOG.md
          fi

          # Add new git commit
          git add VERSION
          git config --global user.name "dependabot[bot]"
          git config --global user.email "dependabot[bot]@users.noreply.github.com"
          git commit -m "[Automated] Increment Version"
        working-directory: actions-runner

      - name: Push increment version commit
        if: ${{ !steps.check_modified.outputs.version_modified && github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'dependabot') }}
        uses: ad-m/github-push-action@v0.8.0
        with:
          ACT_TOKEN: ${{ secrets.ACT_TOKEN }}
          branch: ${{ github.head_ref }}

  merge:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge Dependabot PR
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git merge --no-ff ${{ github.event.pull_request.head.ref }}

      - name: Delete branch
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: |
          git push origin --delete ${{ github.event.pull_request.head.ref }}