name: Deploy _ to GitHub Pages

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.16'
          
      - name: Install Dependencies
        run: npm install
        
      - name: webpack Build
        run: CI= npm run build -- --base=${{ github.event.repository.name }}
        
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          publish_dir: ./build
          github_token: ${{ secrets.GITHUB_TOKEN }}
		  
		  
